"""Shared loaders for the Triple Triad dataset.

Files under data/:
  cards.json   - all 475 cards, generated by extract_wiki.py (source of truth for stats)
  npcs.json    - all 134 NPCs (rules/location/rewards), generated by extract_wiki.py
  decks.json   - MANUAL: npc name -> 5 card names, grown incrementally as you meet NPCs
  collection.json - MANUAL (optional): card names you own, for the deck recommender
"""
from __future__ import annotations

import json
import re

from tt import paths


def _load(name: str, default):
    p = paths.BUNDLED_DATA / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else default


def load_cards() -> list[dict]:
    return _load("cards.json", [])


def load_npcs() -> list[dict]:
    return _load("npcs.json", [])


def load_decks() -> dict:
    decks = dict(_load("decks.json", {}))
    u = paths.user_path("decks.json")
    if paths.FROZEN and u.is_file():
        decks.update(json.loads(u.read_text(encoding="utf-8")))
    return decks


def save_decks(decks: dict) -> None:
    if paths.FROZEN:
        paths.ensure_user_dir()
        target = paths.user_path("decks.json")
    else:
        target = paths.BUNDLED_DATA / "decks.json"
    target.write_text(json.dumps(decks, indent=2, ensure_ascii=False) + "\n")


# --- fuzzy name resolution -------------------------------------------------

def _norm(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"\bcard\b", "", s)
    s = s.replace("&", " and ")
    s = re.sub(r"[^a-z0-9]+", " ", s)
    return s.strip()


class Resolver:
    """Resolve loose user input ('ifrit', '62', 'ultros typhon') to a card dict."""

    def __init__(self, cards: list[dict] | None = None):
        self.cards = cards or load_cards()
        self._by_norm = {}
        self._by_num = {}
        for c in self.cards:
            self._by_norm.setdefault(_norm(c["name"]), c)
            self._by_num[str(c["number"])] = c  # note: 'ff' + 'main' share small numbers

    def resolve(self, q: str) -> dict:
        raw = q.strip()
        if raw.startswith("*") and raw[1:] in self._by_num:
            for c in self.cards:
                if c["series"] == "ff" and str(c["number"]) == raw[1:]:
                    return c
        n = _norm(raw)
        if n in self._by_norm:
            return self._by_norm[n]
        if raw.isdigit():
            hits = [c for c in self.cards if c["series"] == "main" and str(c["number"]) == raw]
            if hits:
                return hits[0]
        subs = [c for k, c in self._by_norm.items() if n and n in k]
        if len(subs) == 1:
            return subs[0]
        if not subs:
            raise KeyError(f"no card matches {q!r}")
        names = ", ".join(sorted(c["name"] for c in subs)[:12])
        raise KeyError(f"{q!r} is ambiguous: {names}")


def find_npc(npcs: list[dict], q: str) -> dict:
    n = q.lower().strip()
    exact = [x for x in npcs if x["name"].lower() == n]
    if exact:
        return exact[0]
    subs = [x for x in npcs if n in x["name"].lower()]
    if len(subs) == 1:
        return subs[0]
    if not subs:
        raise KeyError(f"no NPC matches {q!r}")
    raise KeyError(f"{q!r} is ambiguous: " + ", ".join(x["name"] for x in subs[:12]))
